# Autogenerated file
def render(led_value):
    yield """<!DOCTYPE html>
<html>
  <head>
    <meta charset=\"UTF-8\" />
    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />
    <title>Room Occupation</title>
    <link rel=\"stylesheet\" href=\"static/css/entireframework.min.css\" />
    <link rel=\"stylesheet\" href=\"static/css/index.css\" />
    <script src=\"static/js/index.js\"></script>
	  <script>
        function autoRefresh() """
    yield """{
            window.location = window.location.href;
        }
        setInterval('autoRefresh()', 5000);
    </script>
  </head>
  <body>
    <nav class=\"nav\" tabindex=\"-1\" onclick=\"this.focus()\">
      <div class=\"container\">
        <a class=\"pagename current\" href=\"#\">Ionic Wiznet</a>

      </div>
    </nav>
    <button class=\"btn-close btn btn-sm\">×</button>
    <div class=\"container\">
      <div class=\"hero\">
        <h1 class=\"title\">Room Occupation</h1>
        <div class=\"toggle-div\">
            <p class=\"label\">Status</p>
            <input type=\"checkbox\" id=\"switch\" onclick=\"toggleButtonSwitch()\" """
    if led_value == 1:
        yield """ checked """
    yield """/><label for=\"switch\">Toggle</label>
        </div>
      </div>
    </div>
  </body>
</html>"""
